// Code generated by astest. DO NOT EDIT.

package dockerapi_test

import (
	"testing"

	"cloudeng.io/cicd"
	"cloudeng.io/vms/vmstestutil"
)

func TestInstanceCloneStartStopDelete(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = instanceConfig.Get(t.Name())
	vmstestutil.TestInstanceCloneStartStopDelete(t, cfg)
}

func TestInstanceDeleteFromSuspended(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = instanceConfig.Get(t.Name())
	vmstestutil.TestInstanceDeleteFromSuspended(t, cfg)
}

func TestInstanceExec(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = instanceConfig.Get(t.Name())
	vmstestutil.TestInstanceExec(t, cfg)
}

func TestInstanceLifecycle(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = instanceConfig.Get(t.Name())
	vmstestutil.TestInstanceLifecycle(t, cfg)
}

func TestInstanceStateErrors(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = instanceConfig.Get(t.Name())
	vmstestutil.TestInstanceStateErrors(t, cfg)
}

func TestInstanceSuspendResume(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = instanceConfig.Get(t.Name())
	vmstestutil.TestInstanceSuspendResume(t, cfg)
}
