version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - copyloopvar
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
