test:
  [
    "go",
    "test",
    "-failfast",
    "--covermode=atomic",
    "--vet=off",
    "-race",
    "./...",
  ]
lint: ["golangci-lint", "run", "./..."]
govuln: ["govulncheck", "./..."]
generate: ["go", "generate", "./..."]
markdown: ["gomarkdown", "-overwrite", "./..."]
annotate:
  [
    "goannotate",
    "--config=${MULTIMOD_ROOT}/copyright-annotation.yaml",
    "--annotation=cloudeng-copyright",
  ]
usage: ["gousage", "--overwrite", "./..."]
update: ["go", "get", "-u", "./...", ";", "go", "mod", "tidy"]
