version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  test-linux:
    parameters:
      go:
        type: string
    docker:
      - image: cimg/go:<< parameters.go >>
    steps:
      - checkout
      - run:
          name: test
          command: |
            export USER=circleci
            go run .circleci/runner.go --prep --test

  test-windows:
    executor:
      name: win/default
    steps:
      - run: git config --global core.autocrlf false
      - checkout
      - run:
          name: test
          command: |
            go run .circleci\runner.go --prep --test

  lint:
    parameters:
      go:
        type: string
    docker:
      - image: cimg/go:<< parameters.go >>
    steps:
      - checkout
      - run:
          name: prep
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
            go get github.com/matthewloring/validjson/cmd/validjson@latest
            go install -x github.com/matthewloring/validjson/cmd/validjson@latest
            go run .circleci/runner.go --prep
      - run:
          name: lint
          command: |
            for pkg in $(go run .circleci/runner --modules); do \
              cd $$pkg; \
              golangci-lint run ./...; \
              validjson ./...; \
              cd ..; \
            done

workflows:
  main:
    jobs:
      - test-linux:
          matrix:
            parameters:
              go: ["1.16", "1.17"]
      - test-windows
      - lint:
          matrix:
            parameters:
              go: ["1.17"]
