version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  test-linux:
    parameters:
      go:
        type: string
    docker:
      - image: cimg/go:<< parameters.go >>
    parallelism: 4
    steps:
      - checkout
      - run:
          name: test
          command: |
            export USER=circleci
            go run .circleci/runner.go --prep --test

  lint:
    parameters:
      go:
        type: string
    docker:
      - image: cimg/go:<< parameters.go >>
    parallelism: 4
    steps:
      - checkout
      - run:
          name: prep
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
            go run .circleci/runner.go --prep
      - run:
          name: lint
          command: |
            for pkg in $(go run .circleci/runner --modules); do \
              cd $$pkg; \
              golangci-lint run ./...; \
              cd ..; \
            done

  vulnerabilities:
    resource_class: large
    parameters:
      go:
        type: string
    docker:
      - image: cimg/go:<< parameters.go >>
    parallelism: 4
    steps:
      - checkout
      - run:
          name: vulnerabilities
          command: |
            go install golang.org/x/vuln/cmd/govulncheck@latest
            for pkg in $(go run .circleci/runner --modules); do \
              cd $$pkg; \
              govulncheck ./...; \
              cd ..; \
            done

workflows:
  build-test-lint-vuln:
    jobs:
      - test-linux:
          matrix:
            parameters:
              go: ["1.18", "1.19"]
      - lint:
          matrix:
            parameters:
              go: ["1.19"]
      - vulnerabilities:
          matrix:
            parameters:
              go: ["1.19"]
