version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  test-linux:
    parameters:
      go:
        type: string
    docker:
      - image: cimg/go:<< parameters.go >>
    steps:
      - checkout
      - run:
          name: test
          command: |
            export USER=circleci
            go run .circlci/runner.go --prep --test

  test-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: test
          command: |
            export USER=circleci
            go run .circlci\runner.go --prep --test

  lint:
    parameters:
      go:
        type: string
    docker:
      - image: cimg/go:<< parameters.go >>
    steps:
      - checkout
      - run:
          name: prep
          command: |
            make -f .circleci/Makefile prep-test prep-lint
      - run:
          name: lint
          command: |
            make -f .circleci/Makefile lint

workflows:
  main:
    jobs:
      - test-linux:
          matrix:
            parameters:
              go: ["1.16", "1.17"]
      - test-windows
      - lint:
          matrix:
            parameters:
              go: ["1.17"]
