// Copyright 2026 cloudeng llc. All rights reserved.
// Use of this source code is governed by the Apache-2.0
// license that can be found in the LICENSE file.

// Code generated by "go generate"; DO NOT EDIT.

// Package vms provides support for working with virtual machines.
// State machine transitions for virtual machine instances.
// Each line lists a state followed by the actions that can be applied
// and the resulting next state. "(waiting)" denotes the ActionNone
// no-op used to poll until an in-progress operation completes.
//
//	Initial         Clone -> Cloning
//	Cloning         (waiting) -> Cloning
//	Starting        (waiting) -> Starting
//	Running         Stop -> Stopping,  Suspend -> Suspending
//	Stopping        (waiting) -> Stopping
//	Stopped         Start -> Starting,  Stop -> Stopped,  Delete -> Deleting
//	Suspending      (waiting) -> Suspending
//	Suspended       Start -> Starting,  Suspend -> Suspended,  Delete -> Deleting
//	Deleting        (waiting) -> Deleting
//	Deleted         Clone -> Cloning
//	ErrorUnknown    Delete -> Deleting
package vms
