//go:build ignore

// gen.go generates doc_gen.go, which contains a doc comment
// describing the package and all valid state machine transitions.
// Run via: go generate cloudeng.io/vms
package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"cloudeng.io/vms"
)

func main() {
	var buf bytes.Buffer
	vms.PrintStates(&buf)

	var out strings.Builder
	out.WriteString("// Code generated by \"go generate\"; DO NOT EDIT.\n\n")
	out.WriteString("// Package vms provides support for working with virtual machines.\n")
	out.WriteString("// State machine transitions for virtual machine instances.\n")
	out.WriteString("// Each line lists a state followed by the actions that can be applied\n")
	out.WriteString("// and the resulting next state. \"(waiting)\" denotes the ActionNone\n")
	out.WriteString("// no-op used to poll until an in-progress operation completes.\n")
	out.WriteString("//\n")
	for _, line := range strings.Split(strings.TrimRight(buf.String(), "\n"), "\n") {
		fmt.Fprintf(&out, "//\t%s\n", line)
	}
	out.WriteString("package vms\n")

	if err := os.WriteFile("doc_gen.go", []byte(out.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen: %v\n", err)
		os.Exit(1)
	}
}
