// Code generated by astest. DO NOT EDIT.

package vmstestutil_test

import (
	"testing"

	"cloudeng.io/vms/vmstestutil"
)

func TestInstanceCloneStartStopDelete(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cfg = instanceTestConfig
	vmstestutil.TestInstanceCloneStartStopDelete(t, cfg)
}

func TestInstanceDeleteFromSuspended(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cfg = instanceTestConfig
	vmstestutil.TestInstanceDeleteFromSuspended(t, cfg)
}

func TestInstanceExec(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cfg = instanceTestConfig
	vmstestutil.TestInstanceExec(t, cfg)
}

func TestInstanceLifecycle(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cfg = instanceTestConfig
	vmstestutil.TestInstanceLifecycle(t, cfg)
}

func TestInstanceSuspendResume(t *testing.T) {
	var cfg vmstestutil.InstanceTestConfig
	cfg = instanceTestConfig
	vmstestutil.TestInstanceSuspendResume(t, cfg)
}
