// Code generated by astest. DO NOT EDIT.

package vmstestutil_test

import (
	"testing"

	"cloudeng.io/vms/vmstestutil"
)

func TestAcquireAndRelease(t *testing.T) {
	vmstestutil.TestAcquireAndRelease(t)
}

func TestClose(t *testing.T) {
	vmstestutil.TestClose(t)
}

func TestConcurrentAcquire(t *testing.T) {
	vmstestutil.TestConcurrentAcquire(t)
}

func TestContextCancellation(t *testing.T) {
	vmstestutil.TestContextCancellation(t)
}

func TestExec(t *testing.T) {
	vmstestutil.TestExec(t)
}

func TestLifecycle(t *testing.T) {
	vmstestutil.TestLifecycle(t)
}

func TestStartAndAcquire(t *testing.T) {
	vmstestutil.TestStartAndAcquire(t)
}
