// Code generated by astest. DO NOT EDIT.

package vmstestutil_test

import (
	"testing"

	"cloudeng.io/vms/vmstestutil"
)

func TestLifecycle(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cfg = testConfig
	vmstestutil.TestLifecycle(t, cfg)
}

func TestPoolAcquireAndRelease(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cfg = testConfig
	vmstestutil.TestPoolAcquireAndRelease(t, cfg)
}

func TestPoolClose(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cfg = testConfig
	vmstestutil.TestPoolClose(t, cfg)
}

func TestPoolConcurrentAcquire(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cfg = testConfig
	vmstestutil.TestPoolConcurrentAcquire(t, cfg)
}

func TestPoolContextCancellation(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cfg = testConfig
	vmstestutil.TestPoolContextCancellation(t, cfg)
}

func TestPoolExec(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cfg = testConfig
	vmstestutil.TestPoolExec(t, cfg)
}

func TestPoolStartAndAcquire(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cfg = testConfig
	vmstestutil.TestPoolStartAndAcquire(t, cfg)
}
