// Code generated by astest. DO NOT EDIT.

package dockervm_test

import (
	"testing"

	"cloudeng.io/cicd"
	"cloudeng.io/vms/vmstestutil"
)

func TestPoolAcquireExecRelease(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolAcquireExecRelease(t, cfg)
}

func TestPoolClose(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolClose(t, cfg)
}

func TestPoolConcurrentAcquire(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolConcurrentAcquire(t, cfg)
}

func TestPoolContextCancellation(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolContextCancellation(t, cfg)
}
