name: lint-govulncheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: env
        run: pwd; ls

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config .golangci.yml $(for module in $(go run .circleci/runner.go --modules); do echo ./$module/...; done)

      - name: Vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          for module in $(go run .circleci/runner.go --modules); do;
            cd $module;
            govulncheck ./...;
            cd ..;
          done
