name: go-linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test-lint:
    uses: cloudengio/.github/.github/workflows/go-test-multimod.yml@main
    with:
      runner: |
        [ "self-hosted", "linux", "arm64" ]
      go-versions: |
        [ "1.26.x" ]
      with-webapp: true
      pebble-version: "v2.8.0"
      with-lint: true
      with-govuln: true

#  lint:
#    uses: cloudengio/.github/.github/workflows/go-lint-multimod.yml@main
#    with:
#      runner: |
#        [ "self-hosted", "linux", "arm64" ]
#      go-version: "1.26.x"
